### ISSUE TITLE
ValueTypeNonOverridenCallRule incorrectly flags static calls

### ISSUE THREAD

**Issue by SolalPirelli** [microsoft/RoslynClrHeapAllocationAnalyzer#17]
For instance, `Enum.GetUnderlyingType` is flagged as a non-overriden virtual method, which is clearly incorrect.

(nice work on this extension, by the way!)

**Comment by mjsabby** [comment]
Indeed, that is not right. I welcome a pull request, or I should get to it over the weekend.

(Thanks!)

**Comment by cezarypiatek** [comment]
@mjsabby I guess this was solved by #87, could you close it?

**Comment by mjsabby** [comment]
I do not think this is solved by any of the recent fixes. Do you have a test to show otherwise?

**Comment by cezarypiatek** [comment]
I'm sorry my mistake, I was going to point to #37. There is a test called `CallSiteImplicitAllocation_DoNotReportNonOverriddenMethodCallForStaticCalls` which prove that it was fixed.
