### ISSUE TITLE
Use Number Codes for Issues instead of Long names

### ISSUE THREAD

**Issue by SamuelEnglard** [microsoft/RoslynClrHeapAllocationAnalyzer#28]
`HeapAnalyzerExplicitNewArrayRule` should be HAA0001 for example. Makes working with them hard

**Comment by mjsabby** [comment]
Agreed, PRs welcome. I've made this an enhancement request.

**Comment by cezarypiatek** [comment]
@mjsabby It looks like this issue had been fixed by #41. Could you close it?
