### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/RoslynClrHeapAllocationAnalyzer#29]
Is this coming? Also I noticed there has not been any updates for about 10 months. Is this project unmaintained?

**Comment by aalmada** [comment]
The analyzer can be installed using NuGet: https://www.nuget.org/packages/ClrHeapAllocationAnalyzer/

**Comment by ygeelen-tb** [comment]
Is there no VS 2017 extension coming then?

**Comment by aalmada** [comment]
I have no idea about the extension but it looks like NuGet is the new prefered method of distribution.

**Comment by RehanSaeed** [comment]
Agreed, the NuGet package is the way to go. It works on build machines too.

**Comment by mjsabby** [comment]
The project is maintained. Any PRs are welcome, but the next steps will be to improve usability in VS 2017 because currently it is overwhelming to use in projects of large sizes because there are so many warning types.
