### ISSUE TITLE
Visual Studio Market Place: typo in extension description

### ISSUE THREAD

**Issue by jawn** [microsoft/RoslynClrHeapAllocationAnalyzer#60]
Couldn't find a place to fix as a PR, so logging an issue instead.

## Steps to reproduce

Go to https://marketplace.visualstudio.com/items?itemName=MukulSabharwal.ClrHeapAllocationAnalyzer

## Actual result:
First word in overview is "Rosly" (without n)

![image](https://user-images.githubusercontent.com/1705112/48059574-d4c9e280-e1b9-11e8-9eb9-3afbb60834b2.png)

## Expected result
First word in overview is "Roslyn"

**Comment by drewnoakes** [comment]
This has been addressed and can now be closed.
