### ISSUE TITLE
Installation Fails in Visual Studio 2019 Enterprise - Version 16.0.0 Preview 4.2

### ISSUE THREAD

**Issue by agatlin** [microsoft/RoslynClrHeapAllocationAnalyzer#68]
The Install fails with the following message:

```
This extension cannot be installed because the following references are missing:
Microsoft.VisualStudio.Components.Roslyn.LanguageServices.
```

Just as an FYI, the lack of availability of this component is causing other Rolyn-related extensions to also fail to install.

**Comment by set-webmaster** [comment]
Same problem, cannot install for VS 2019

**Comment by RedlineTriad** [comment]
Same issue.
Visual Studio Enterprise 2019 16.1.0 Preview 3.0

**Comment by mjsabby** [comment]
I have uploaded a new release. Please give that a try. https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer/releases/tag/2.0

**Comment by Nekromancer** [comment]
Seems to be working great now, thanks :)
